language: android
android:
  components:
    - build-tools-19.1.0
    - android-19
node_js:
- '0.10'
before_install: npm install -g cordova ionic
install: npm install
before_script:
    - ionic platform android
    - cp platforms/AndroidManifest.xml platforms/android/AndroidManifest.xml
script: cordova build --release android
before_deploy:
    - git fetch --tags
    - cp platforms/android/ant-build/LogicalFallacy-release-unsigned.apk platforms/android/ant-build/LogicalFallacy.apk
deploy:
  provider: releases
  api_key:
    secure: fc7c074e60236b9c70c0fddc3734e9aa55a8db54
  file: platforms/android/ant-build/LogicalFallacy.apk
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: ciwchris/your-logical-fallacy-is
