language: android
android:
  components:
    - build-tools-19.1.0
    - android-19
node_js:
- '0.10'
before_install:
    - npm install -g cordova ionic
install: npm install
before_script:
    - ionic platform android
    - cordova platform rm android
    - cordova platform add android
    - cp platforms/AndroidManifest.xml platforms/android/AndroidManifest.xml
    - git fetch --tags
script: cordova build --release android
# Doesn't seem to exist on travis ci yet
#before_deploy: zipalign -v 4 platforms/android/ant-build/LogicalFallacy-release-unsigned.apk platforms/android/ant-build/LogicalFallacy.apk
deploy:
  provider: releases
  api_key:
    secure: fc7c074e60236b9c70c0fddc3734e9aa55a8db54
  file: platforms/android/ant-build/LogicalFallacy.apk
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: ciwchris/your-logical-fallacy-is
